# Docker Compose file for development
version: "2"
services:

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../data/replication_packets:/data/replication_packets
      - ../data/logos:/code/metabrainz/static/img/user_logos
      - ..:/code
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
      - mail

  db:
    build:
      context: ./pg_custom/
      dockerfile: Dockerfile
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: metabrainz
      POSTGRES_PASSWORD: metabrainz
      POSTGRES_DB: metabrainz
    ports:
      - "15432:5432"

  redis:
    image: redis:3.2.1

  mail:
    build:
      context: ./smtp/
      dockerfile: Dockerfile
    environment:
      MAILDOMAIN: metabrainz.org
    ports:
      - "25:25"
